import type { Metadata } from "next";
import { Bree_Serif } from "next/font/google";
import "../globals.css";
import Header from "./Header";
import { ThemeProvider } from "@/providers/theme";

const bree = Bree_Serif({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className={`mx-5 ${bree.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="mx-auto max-w-4xl p-1 xl:p-0">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
